services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - ./env/common.env
      - ./env/secrets.env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  app:
    build: .
    restart: always
    env_file:
      - ./env/common.env
      - ./env/site.env
      - ./env/secrets.env
    ports:
      - "${APP_HOST_PORT}:3000"
    depends_on:
      - db
    command: npm start

volumes:
  db-data:
